// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYy5QE4YJ91jx4lJOqqmyTWlGViJ1O1B0',
    appId: '1:721437511231:web:441fab3ac0b887248a328a',
    messagingSenderId: '721437511231',
    projectId: 'pre-trip-inspection-cba6d',
    authDomain: 'pre-trip-inspection-cba6d.firebaseapp.com',
    storageBucket: 'pre-trip-inspection-cba6d.firebasestorage.app',
    measurementId: 'G-6QEHEKTYN6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Sahnrie1jaxHSe7fwRwOvb9fspUsMbo',
    appId: '1:721437511231:ios:15d0fb660b8fc47a8a328a',
    messagingSenderId: '721437511231',
    projectId: 'pre-trip-inspection-cba6d',
    storageBucket: 'pre-trip-inspection-cba6d.firebasestorage.app',
    iosBundleId: 'com.example.ptiMobileApp',
  );

}